+ release v1.0.0
ustkit/gomac pull request #1
Opened 2022-06-24 02:02 UTC by ustkit

2022-06-24 13:55 UTC, blattaria7 commented on internal/gophermart/repositories/postgresql.go
> +	return
тут хорошо бы более явно возвращать результат)

2022-06-24 14:35 UTC, blattaria7 requested changes
Очень хорошая работа! Мне нравится, как спроектирована архитектура сервиса и само расположение файлов. По всем пунктам definition of done все отлично - здорово реализован пакет с логгером, есть миграции и логично добавлены юниты.

Но необходимо поправить работу с контекстом, потому отправляю задание на доработку. И также оставила несколько косметических замечаний, которые стоит учесть)

2022-06-24 14:35 UTC, blattaria7 commented on internal/gophermart/repositories/postgresql.go
> +	ctx context.Context
нельзя контекст передавать как поле структуры, это противоречит самой идее работы контекста - контекст должен передаваться в аргументах функции с уровней выше. и его нужно будет убрать из структуры и конструктора для нее
почитай [как он устроен под капотом](https://habr.com/ru/post/269299/) =)

2022-06-24 14:35 UTC, blattaria7 commented on internal/gophermart/logger/logger.go
> +package logger
пакеты с юнитами правильнее называть в формате`[имя_тестируемого_пакета]_test`

[Здесь](https://habr.com/ru/company/otus/blog/452772/) в главе _Используйте отдельный пакет _test_ написано почему стоит так делать)

2022-06-24 14:35 UTC, blattaria7 commented on internal/gophermart/models/client.go
> +	if len(r.Login) > 64 {
не понятно что за число 64. Надо вынести его в константу выше и сделать явное название)

2022-06-24 14:35 UTC, blattaria7 commented on internal/gophermart/services/loyalty.go
> +		if statusCode != 200 {
200  =>`http.StatusOK`

2022-06-24 14:35 UTC, blattaria7 commented on cmd/gophermart/main.go
> +	g, gCtx := errgroup.WithContext(ctx)
лучше g заменить на что-то более полное, например `errGroup` и `errGroupCtx`

2022-06-25 03:59 UTC, ustkit commented on cmd/gophermart/main.go
> +	ctx, _ := signal.NotifyContext(context.Background(), syscall.SIGTERM, syscall.SIGINT, syscall.SIGQUIT)
здесь вторым параметром возвращается cancel function, а не ошибка

2022-06-25 04:01 UTC, ustkit commented on internal/gophermart/repositories/postgresql.go
> +	return
Исправил

2022-06-25 04:02 UTC, ustkit commented on internal/gophermart/repositories/postgresql.go
> +		switch err.(*pgconn.PgError).SQLState() {
Исправил

2022-06-25 04:02 UTC, ustkit commented on internal/gophermart/logger/logger.go
> +package logger
Исправил

2022-06-25 04:02 UTC, ustkit commented on internal/gophermart/models/client.go
> +	if len(r.Login) > 64 {
Исправил

2022-06-25 04:02 UTC, ustkit commented on internal/gophermart/services/loyalty.go
> +		if statusCode != 200 {
Исправил

2022-06-25 04:02 UTC, ustkit commented on internal/gophermart/repositories/postgresql.go
> +func NewRepositoryPostgreSQL(ctx context.Context, dsn string) (repo Repo, err error) {
Исправил

2022-06-25 04:03 UTC, ustkit commented on cmd/gophermart/main.go
> +	g, gCtx := errgroup.WithContext(ctx)
Исправил

2022-06-25 04:24 UTC, ustkit commented on internal/gophermart/repositories/postgresql.go
> +	ctx context.Context
Исправил

2022-06-25 04:24 UTC, ustkit commented on internal/gophermart/services/loyalty.go
> +	Ctx     context.Context
Исправил

2022-06-27 06:08 UTC, blattaria7 commented on cmd/gophermart/main.go
> +	g, gCtx := errgroup.WithContext(ctx)
errGroupCtx, gCtx => errGroup, errGroupCtx, вот так было бы правильней)

2022-06-27 06:16 UTC, blattaria7 commented on cmd/gophermart/main.go
> +	ctx, _ := signal.NotifyContext(context.Background(), syscall.SIGTERM, syscall.SIGINT, syscall.SIGQUIT)
прошу прощения за некорректное замечание

cancel тоже не стоит мьютить, иначе при создании дочернего контекста этот контекст будет жить вечно (будет утечка контекста)

надо всегда вызывать cancel

2022-06-27 06:20 UTC, blattaria7 commented on internal/gophermart/repositories/postgresql.go
> +		switch err.(*pgconn.PgError).SQLState() {
теперь получается, что эта проверка просто есть и ничего не возвращает...
стоит ее убрать под условие `if errors.As(err, &pgErr) {` и в нем делать switch)

2022-06-27 06:22 UTC, blattaria7 requested changes
Вижу, что бОльшая часть комментариев учтена, но нужно доработать еще буквально три момента)

2022-06-27 06:26 UTC, blattaria7 commented on cmd/gophermart/main.go
> +	ctx, _ := signal.NotifyContext(context.Background(), syscall.SIGTERM, syscall.SIGINT, syscall.SIGQUIT)
вот [тут](https://go.dev/src/context/context.go?s=9162:9288) в самом начале это объясняется 

если интересно разобраться как это работает на практике - можно попробовать включить профилировщик и запустить контекстов в цикле без отмены и посмотреть, что будет)

2022-06-27 07:05 UTC, ustkit commented on cmd/gophermart/main.go
> +	g, gCtx := errgroup.WithContext(ctx)
Исправил. Мне стыдно (

2022-06-27 07:28 UTC, ustkit commented on internal/gophermart/repositories/postgresql.go
> +		switch err.(*pgconn.PgError).SQLState() {
Исправил. Тут тоже стыдно. Вообще убрал switch.

2022-06-27 07:29 UTC, ustkit commented on cmd/gophermart/main.go
> +	ctx, _ := signal.NotifyContext(context.Background(), syscall.SIGTERM, syscall.SIGINT, syscall.SIGQUIT)
Спасибо за "при создании дочернего контекста этот контекст будет жить вечно (будет утечка контекста)"
Осознал. Исправил.

2022-06-27 10:12 UTC, blattaria7 approved these changes
Не стоит переживать из-за ошибок, все хорошо, в этом ведь и заключается основная задача курса - учиться и узнавать новые вещи))
 
Прекрасная работа! Все доработки учтены, ставлю аппрув =)
И поздравляю с успешным прохождением курса! 🥳

2022-06-27 11:20 UTC, merged